language: java
jdk:
  - openjdk7
before_install:
  - sudo rm -f /usr/local/gradle/bin/gradle
  - sudo add-apt-repository -y ppa:cwchien/gradle
  - sudo apt-get update -qq
  - sudo apt-get install -qq gradle-2.1
  - gradle --version